/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.pwt5ca.jeda;

import me.pwt5ca.jeda.fsm.DebugState;
import me.pwt5ca.jeda.fsm.FiniteStateMachine;
import me.pwt5ca.jeda.fsm.FiniteStateMachineBuilder;
import me.pwt5ca.jeda.fsm.State;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        FiniteStateMachineBuilder builder = new FiniteStateMachineBuilder();
        // State start = builder.newState();
        // start.setLabel("Start");
        // State end = builder.newState();
        // end.setLabel("End");

        State start = new DebugState("Start");
        builder.addState(start);
        State end = new DebugState("End");
        builder.addState(end);

        builder.addBinaryTransition(start, end, start);
        builder.addBinaryTransition(end, start, end);
        FiniteStateMachine fsm = builder.build();

        // System.out.println(fsm.toDot());
        // Write to file
        try {
            java.io.FileWriter writer = new java.io.FileWriter("fsm.dot");
            writer.write(fsm.toDot());
            writer.close();

            // Run dot
            ProcessBuilder pb = new ProcessBuilder("dot", "-Tpng", "fsm.dot", "-o", "fsm.png");
            Process p = pb.start();
            p.waitFor();
        } catch (java.io.IOException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        } catch (InterruptedException e) {
            System.out.println("An error occurred.");
            e.printStackTrace();
        }

        for (int i = 0; i < 10; i++) {
            Boolean input = i % 2 == 0;
            System.out.println("Input: " + input);
            fsm.evaluate(input);
        }
    }
}
