name: Gradle tests
run-name: ${{ github.event.pull_request.title }} Gradle tests

on:
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: "19"
          distribution: "adopt"
      - name: Run tests
        run: ./gradlew test
